-- Database Schema per DroneTech

CREATE DATABASE IF NOT EXISTS dronetech;
USE dronetech;

CREATE TABLE CLIENTE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(50),
  Cognome VARCHAR(50),
  Email VARCHAR(100),
  Telefono VARCHAR(20),
  Tipo ENUM('Privato', 'Azienda'),
  CodiceFiscale_PIVA VARCHAR(30)
);

CREATE TABLE FORNITORE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(100),
  Email VARCHAR(100),
  Telefono VARCHAR(20)
);

CREATE TABLE DRONE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Modello VARCHAR(100),
  Marca VARCHAR(50),
  Prezzo DECIMAL(10,2),
  Stato ENUM('Disponibile', 'Noleggiato', 'Venduto', 'InRiparazione'),
  ID_Fornitore INT,
  FOREIGN KEY (ID_Fornitore) REFERENCES FORNITORE(ID)
);

CREATE TABLE RIPARAZIONE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_Drone INT,
  DataIngresso DATE,
  Descrizione TEXT,
  Stato ENUM('In Corso', 'Completata'),
  Costo DECIMAL(10,2),
  FOREIGN KEY (ID_Drone) REFERENCES DRONE(ID)
);

CREATE TABLE ORDINE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_Cliente INT,
  ID_Drone INT,
  Tipo ENUM('Vendita', 'Noleggio'),
  Data DATE,
  DataInizio DATE,
  DataFine DATE,
  FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID),
  FOREIGN KEY (ID_Drone) REFERENCES DRONE(ID)
);

CREATE TABLE CORSO_DI_PILOTAGGIO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Titolo VARCHAR(100),
  Livello ENUM('Base', 'Intermedio', 'Avanzato'),
  Prezzo DECIMAL(10,2),
  DataInizio DATE,
  DurataOre INT
);

CREATE TABLE PRENOTAZIONE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_Cliente INT,
  ID_Corso INT,
  DataPrenotazione DATE DEFAULT CURDATE(),
  FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID),
  FOREIGN KEY (ID_Corso) REFERENCES CORSO_DI_PILOTAGGIO(ID)
);

CREATE TABLE PERSONALE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(50),
  Cognome VARCHAR(50),
  Ruolo VARCHAR(50),
  Email VARCHAR(100),
  Telefono VARCHAR(20)
);

CREATE TABLE ISTRUTTORE_CORSO (
  ID_Istruttore INT,
  ID_Corso INT,
  PRIMARY KEY(ID_Istruttore, ID_Corso),
  FOREIGN KEY (ID_Istruttore) REFERENCES PERSONALE(ID),
  FOREIGN KEY (ID_Corso) REFERENCES CORSO_DI_PILOTAGGIO(ID)
);

CREATE TABLE SERVIZIO_FOTOGRAFICO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_Cliente INT,
  TipoEvento VARCHAR(100),
  DataEvento DATE,
  Luogo VARCHAR(100),
  Prezzo DECIMAL(10,2),
  FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID)
);

CREATE TABLE CARRELLO_TEMP (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_Cliente INT,
  ID_Drone INT,
  DataAggiunta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID),
  FOREIGN KEY (ID_Drone) REFERENCES DRONE(ID)
);
